import { useEffect, useState } from 'react'

type Report={id:string;postId:string;symbol:string;title:string;excerpt:string;reporterNickname:string;reason:string;details:string|null;status:string;createdAt:string;hidden:boolean}
type ReportPage={content:Report[];page:number;totalPages:number;totalElements:number}
const labels:Record<string,string>={SPAM:'스팸',ABUSE:'욕설·혐오',PERSONAL_INFO:'개인정보 노출',OTHER:'기타'}
export default function DiscussionModeration({token}:{token:string}){
 const [page,setPage]=useState(0);const [data,setData]=useState<ReportPage>({content:[],page:0,totalPages:0,totalElements:0});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0)
 useEffect(()=>{const c=new AbortController();fetch('/api/admin/discussion-reports?page='+page,{headers:{Authorization:'Bearer '+token},signal:c.signal}).then(async r=>{if(!r.ok)throw Error();setData(await r.json())}).catch(e=>{if(e.name!=='AbortError')setError('신고 목록을 불러오지 못했습니다.')});return()=>c.abort()},[token,page,revision])
 async function resolve(id:string,action:'HIDE'|'DISMISS'|'RESTORE'){setBusy(true);setError('');try{const r=await fetch('/api/admin/discussion-reports/'+id,{method:'PATCH',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action,reason:action==='HIDE'?'신고 검토 결과 관리자 숨김 처리':''})});if(!r.ok)throw Error();setRevision(x=>x+1)}catch{setError('신고를 처리하지 못했습니다. 목록을 새로고침한 뒤 다시 확인해 주세요.')}finally{setBusy(false)}}
 return <section className="space-y-4" aria-labelledby="moderation-title"><div><h2 className="page-heading" id="moderation-title">토론방 신고 관리</h2><p className="panel-description">신고된 종목 게시글을 검토하고 숨김, 기각, 복원 처리합니다. 전체 {data.totalElements}건</p></div>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{data.content.length===0?<p className="panel-card text-sm text-slate-600">이 페이지에 신고가 없습니다.</p>:<ol className="space-y-3">{data.content.map(r=><li key={r.id} className="panel-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-slate-500">{r.symbol} · {labels[r.reason]??r.reason} · {r.reporterNickname} · {new Date(r.createdAt).toLocaleString('ko-KR')}</p><h3 className="mt-1 font-semibold">{r.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{r.excerpt}</p>{r.details&&<p className="mt-2 text-sm text-slate-500">신고 내용: {r.details}</p>}<p className="mt-2 text-xs text-slate-500">상태: {r.status}</p></div><div className="flex flex-wrap gap-2">{r.status==='PENDING'&&<><button className="primary-button" type="button" disabled={busy} onClick={()=>void resolve(r.id,'HIDE')}>게시글 숨김</button><button className="secondary-button" type="button" disabled={busy} onClick={()=>void resolve(r.id,'DISMISS')}>신고 기각</button></>}{r.status==='HIDDEN'&&<button className="secondary-button" type="button" disabled={busy} onClick={()=>void resolve(r.id,'RESTORE')}>게시글 복원</button>}</div></div></li>)}</ol>}{data.totalPages>1&&<nav className="flex items-center justify-between" aria-label="신고 페이지"><button className="secondary-button" disabled={page===0||busy} onClick={()=>setPage(x=>x-1)}>이전</button><span>{page+1} / {data.totalPages}</span><button className="secondary-button" disabled={page+1>=data.totalPages||busy} onClick={()=>setPage(x=>x+1)}>다음</button></nav>}</section>
}
