import { useEffect, useLayoutEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { useQuery } from '@tanstack/react-query'
import type { CoinSymbol, Exchange } from './RecommendationPanel'
import type { MarketStream } from './useMarketStream'
import { venues } from './useMarketStream'
import MarketDiscussionBoard from './MarketDiscussionBoard'

type Candle = { openedAt: string; open: number; high: number; low: number; close: number; volume: number }
type Listing = { market: string; koreanName: string; englishName: string }
type Props = { exchange: Exchange; symbol: CoinSymbol; onExchangeChange: (exchange: Exchange) => void; onSymbolChange: (symbol: CoinSymbol) => void; stream: MarketStream; onPriceSelect?: (price: number, side: 'BUY' | 'SELL') => void; orderPanel?: ReactNode; token?: string | null }
const intervals = [{ id: '1m', label: '1분' }, { id: '3m', label: '3분' }, { id: '5m', label: '5분' }, { id: '10m', label: '10분' }, { id: '15m', label: '15분' }, { id: '30m', label: '30분' }, { id: '60m', label: '1시간' }, { id: '240m', label: '4시간' }, { id: '1d', label: '일' }, { id: '1w', label: '주' }, { id: '1M', label: '월' }]
const priceText = (value: number) => '₩' + value.toLocaleString('ko-KR', { maximumFractionDigits: value < 1 ? 8 : 0 })
const quantityText = (value: number) => value.toLocaleString('ko-KR', { maximumFractionDigits: 8 })
const relativeToOpen = (price: number, open: number | null | undefined) => open && open > 0 ? (price / open - 1) * 100 : null
const relativeText = (value: number | null) => value === null ? '시가 대기' : `${value > 0 ? '+' : ''}${value.toFixed(2)}%`
const timeText = (value: number | string) => new Date(value).toLocaleString('ko-KR')
function mean(values: number[]) { return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null }
function rsi14(closes: number[]) {
  if (closes.length < 15) return null
  const recent = closes.slice(-15), changes = recent.slice(1).map((close, index) => close - recent[index])
  const averageGain = mean(changes.map((value) => Math.max(0, value))) ?? 0
  const averageLoss = mean(changes.map((value) => Math.max(0, -value))) ?? 0
  return averageLoss === 0 ? 100 : 100 - 100 / (1 + averageGain / averageLoss)
}

/** 공개 캔들·체결·호가를 시각화하며 주문이나 개인 체결 내역은 다루지 않는다. */
export default function MarketTradingPanel({ exchange, symbol, onExchangeChange, onSymbolChange, stream, onPriceSelect, orderPanel, token }: Props) {
  const [interval, setInterval] = useState('1d')
  const [style, setStyle] = useState<'candle' | 'line' | 'area'>('candle')
  const [showSma7, setShowSma7] = useState(true)
  const [showSma30, setShowSma30] = useState(false)
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null)
  const [zoom, setZoom] = useState(1)
  const [showZoomTip, setShowZoomTip] = useState(() => localStorage.getItem('chart-zoom-tip-dismissed') !== 'true')
  const chartRef = useRef<SVGSVGElement>(null)
  const pinchDistance = useRef<number | null>(null)
  const [depth, setDepth] = useState<'normal' | 'cumulative'>('normal')
  const [search, setSearch] = useState('')
  const orderbookViewport = useRef<HTMLDivElement>(null)
  const scrollTimer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const [scrollingOrderbook, setScrollingOrderbook] = useState(false)
  const centeredBook = useRef<string | null>(null)
  const market = `KRW-${symbol}`
  const marketQuery = useQuery({ queryKey: ['market-list', exchange], retry: false, staleTime: 300_000, queryFn: async () => { const response = await fetch(`/api/markets/${exchange}/markets`); if (!response.ok) throw new Error('markets'); return response.json() as Promise<Listing[]> } })
  const listings = Array.isArray(marketQuery.data) ? marketQuery.data : []
  const filteredListings = listings.filter((item) => `${item.market} ${item.koreanName} ${item.englishName}`.toLowerCase().includes(search.toLowerCase()))
  useEffect(() => { const available = marketQuery.data; if (marketQuery.isSuccess && available?.length && !available.some((item) => item.market === market)) onSymbolChange(available[0].market.slice(4)) }, [marketQuery.data, marketQuery.isSuccess, market, onSymbolChange])
  const ticker = stream.tickers[exchange]
  const trades = stream.trades[exchange] ?? []
  const orderbook = stream.orderbooks[exchange] ?? []
  const candleQuery = useQuery({ queryKey: ['market-candles', exchange, market, interval], retry: false, staleTime: 10_000, refetchInterval: interval.endsWith('m') ? 15_000 : 60_000, queryFn: async () => { const response = await fetch(`/api/markets/${exchange}/candles?market=${market}&interval=${interval}&count=100`); if (!response.ok) throw new Error('candles'); return response.json() as Promise<Candle[]> } })
  const dailyQuery = useQuery({ queryKey: ['market-daily-statistics', symbol], retry: false, staleTime: 60_000, refetchInterval: 300_000, queryFn: async () => Promise.all((['UPBIT', 'BITHUMB'] as const).map(async (venue) => { const response = await fetch('/api/markets/' + venue + '/candles?market=KRW-' + symbol + '&interval=1d&count=8'); if (!response.ok) throw new Error('daily candles'); return [venue, (await response.json() as Candle[]).sort((a, b) => Date.parse(b.openedAt) - Date.parse(a.openedAt))] as const })) })
  const candles = (Array.isArray(candleQuery.data) ? [...candleQuery.data] : []).sort((a, b) => Date.parse(a.openedAt) - Date.parse(b.openedAt))
  const closes = candles.map((candle) => candle.close)
  const maxZoom = Math.max(1, candles.length / 12)
  const chartCandles = candles.slice(-Math.max(12, Math.floor(candles.length / zoom)))
  const sma7 = mean(closes.slice(-7)), sma30 = closes.length >= 30 ? mean(closes.slice(-30)) : null, rsi = rsi14(closes)
  const periodChange = closes.length > 1 ? (closes.at(-1)! / closes[0] - 1) * 100 : null
  const chartWidth = 700, top = 16, priceHeight = 172, volumeTop = 207, volumeHeight = 38
  const allPrices = chartCandles.flatMap((candle) => [candle.low, candle.high]); if (ticker) allPrices.push(ticker.price)
  const high = Math.max(...allPrices, 1), low = Math.min(...allPrices, high * 0.999)
  const y = (value: number) => top + ((high - value) / (high - low || 1)) * priceHeight
  const step = chartWidth / Math.max(chartCandles.length, 1), bodyWidth = Math.min(12, step * 0.58)
  const maxVolume = Math.max(...candles.map((candle) => candle.volume), 1)
  const closePoints = chartCandles.map((candle, index) => `${20 + step * index + step / 2},${y(candle.close)}`).join(' ')
  const chartOffset = candles.length - chartCandles.length
  const maPoints = (period: number) => chartCandles.map((_, index) => { const candleIndex = chartOffset + index; const avg = mean(closes.slice(Math.max(0, candleIndex - period + 1), candleIndex + 1))!; return `${20 + step * index + step / 2},${y(avg)}` }).join(' ')
  const selected = selectedIndex === null ? null : chartCandles[selectedIndex]
  const asks = orderbook.filter((level) => level.askPrice > 0 && level.askSize >= 0).sort((a, b) => a.askPrice - b.askPrice).slice(0, 15)
  const bids = orderbook.filter((level) => level.bidPrice > 0 && level.bidSize >= 0).sort((a, b) => b.bidPrice - a.bidPrice).slice(0, 15)
  const askDepth = asks.map((_, index) => asks.slice(0, index + 1).reduce((sum, row) => sum + row.askSize, 0))
  const bidDepth = bids.map((_, index) => bids.slice(0, index + 1).reduce((sum, row) => sum + row.bidSize, 0))
  const maxDepth = Math.max(1, ...(depth === 'cumulative' ? [...askDepth, ...bidDepth] : [...asks.map((level) => level.askSize), ...bids.map((level) => level.bidSize)]))
  useEffect(() => () => { if (scrollTimer.current) clearTimeout(scrollTimer.current) }, [])
  const revealOrderbookScrollbar = () => { setScrollingOrderbook(true); if (scrollTimer.current) clearTimeout(scrollTimer.current); scrollTimer.current = setTimeout(() => setScrollingOrderbook(false), 800) }
  useLayoutEffect(() => { const key = exchange + ':' + symbol; if ((!asks.length && !bids.length) || centeredBook.current === key) return; if (orderbookViewport.current) { orderbookViewport.current.scrollTop = 7 * 40; centeredBook.current = key } }, [exchange, symbol, asks.length, bids.length])
  const changeZoom = (factor: number) => { setZoom(current => Math.max(1, Math.min(maxZoom, current * factor))); setSelectedIndex(null) }
  useEffect(() => { const chart = chartRef.current; if (!chart) return; const onWheel = (event: WheelEvent) => { event.preventDefault(); setZoom(current => Math.max(1, Math.min(maxZoom, current * (event.deltaY < 0 ? 1.2 : 1 / 1.2)))); setSelectedIndex(null) }; chart.addEventListener('wheel', onWheel, { passive: false }); return () => chart.removeEventListener('wheel', onWheel) }, [maxZoom])

  return <section id="market-terminal" className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4" aria-labelledby="market-trading-heading">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-600">{venues[exchange]} 실시간 시장</p><h2 className="mt-1 text-xl font-bold text-slate-950" id="market-trading-heading">{market}</h2></div>
      <label className="grid gap-1 text-sm font-medium">종목<input className="rounded-lg border border-slate-300 px-3 py-2" aria-label="코인 검색" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="심볼 또는 코인명 검색"/><select className="rounded-lg border border-slate-300 bg-white px-3 py-2" aria-label="차트 종목" value={symbol} onChange={(event) => onSymbolChange(event.target.value)}>{filteredListings.map((item) => <option key={item.market} value={item.market.slice(4)}>{item.market.slice(4)} · {item.koreanName}</option>)}</select></label></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-2" role="group" aria-label="거래소 시세 선택">{(['UPBIT', 'BITHUMB'] as const).map((venue) => { const quote = stream.tickers[venue]; return <button key={venue} type="button" aria-pressed={exchange === venue} onClick={() => onExchangeChange(venue)} className={`min-h-16 rounded-lg border p-3 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-700 ${exchange === venue ? 'border-blue-700 bg-blue-50' : 'border-slate-200 bg-slate-50'}`}><span className="flex items-center justify-between gap-2 text-sm"><span>{venues[venue]} · KRW-{symbol}</span><span>{stream.connected[venue] ? '실시간 연결' : '연결 대기'}</span></span><strong className="mt-1 block text-lg text-slate-950">{quote ? priceText(quote.price) : '시세 수신 중'}</strong></button> })}</div>
    <div className="mt-5 grid gap-2 sm:grid-cols-5" aria-label="시장 요약"><Metric label="24시간 등락" value={ticker?.changeRate == null ? '수신 대기' : `${ticker.changeRate >= 0 ? '+' : ''}${ticker.changeRate.toFixed(2)}%`} /><Metric label="시가 대비" value={ticker?.open == null ? '수신 대기' : relativeText(relativeToOpen(ticker.price, ticker.open))} /><Metric label="당일 고가" value={ticker?.high ? priceText(ticker.high) : '수신 대기'} /><Metric label="당일 저가" value={ticker?.low ? priceText(ticker.low) : '수신 대기'} /><Metric label="24시간 거래량" value={ticker?.volume24h ? `${quantityText(ticker.volume24h)} ${symbol}` : '수신 대기'} /></div>
    <div className="mt-4 grid gap-3"><section className="min-w-0" aria-label="Market chart">
<div className="mt-5 flex flex-wrap items-center gap-2" role="group" aria-label="차트 기간">{intervals.map((item) => <button key={item.id} type="button" aria-pressed={interval === item.id} className={`rounded-md px-3 py-2 text-sm font-semibold ${interval === item.id ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-700'}`} onClick={() => { setInterval(item.id); setSelectedIndex(null) }}>{item.label}</button>)}</div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><h3 className="font-bold text-slate-900">{intervals.find((item) => item.id === interval)?.label} 차트 · 최근 {candles.length}개</h3><p className="text-xs text-slate-500" aria-live="polite">{stream.connected[exchange] ? '공개 WebSocket 연결됨' : '공개 WebSocket 연결 중'}{ticker ? ` · 수신 ${timeText(ticker.capturedAt)}` : ''}</p><div className="flex items-center gap-1" aria-label="차트 확대/축소"><button type="button" className="secondary-button px-2 py-1" aria-label="차트 축소" onClick={() => changeZoom(1 / 1.2)} disabled={zoom <= 1}>−</button><span className="min-w-12 text-center text-xs text-slate-500">{Math.round(zoom * 100)}%</span><button type="button" className="secondary-button px-2 py-1" aria-label="차트 확대" onClick={() => changeZoom(1.2)} disabled={zoom >= maxZoom}>+</button></div></div>
    <div className="mt-2 flex flex-wrap items-center gap-4 border-b border-slate-200 pb-3 text-sm"><fieldset className="flex flex-wrap gap-3"><legend className="sr-only">차트 유형</legend>{([['candle', '캔들'], ['line', '선'], ['area', '영역']] as const).map(([key, label]) => <label key={key} className="inline-flex items-center gap-1.5"><input type="radio" name="chart-style" value={key} checked={style === key} onChange={() => setStyle(key)} />{label}</label>)}</fieldset><label className="inline-flex items-center gap-1.5"><input type="checkbox" checked={showSma7} onChange={(event) => setShowSma7(event.target.checked)} />SMA 7</label><label className="inline-flex items-center gap-1.5"><input type="checkbox" checked={showSma30} onChange={(event) => setShowSma30(event.target.checked)} />SMA 30</label></div>
    {showZoomTip && <p className="mt-2 flex items-center justify-between gap-2 rounded-lg bg-blue-50 px-3 py-2 text-sm text-blue-900" role="note">차트에 마우스 휠을 굴리거나 손가락으로 확대·축소할 수 있습니다.<button type="button" className="shrink-0 rounded px-2 py-1 font-semibold hover:bg-blue-100" aria-label="차트 확대 안내 닫기" onClick={() => { localStorage.setItem('chart-zoom-tip-dismissed', 'true'); setShowZoomTip(false) }}>닫기</button></p>}
    {candleQuery.isError && <p className="mt-3 text-sm text-amber-800" role="status">과거 캔들을 불러오지 못했습니다. 공개 실시간 데이터는 계속 수신을 시도합니다.</p>}
    {candles.length ? <div className="mt-2 overflow-x-auto"><svg ref={chartRef} viewBox="0 0 740 258" className="min-w-[620px] w-full" role="img" tabIndex={0} aria-label={`${venues[exchange]} ${market} ${interval} ${style} chart`} data-zoom={zoom.toFixed(2)} style={{ touchAction: 'pan-y' }} onTouchStart={(event) => { if (event.touches.length === 2) pinchDistance.current = Math.hypot(event.touches[0].clientX - event.touches[1].clientX, event.touches[0].clientY - event.touches[1].clientY) }} onTouchMove={(event) => { if (event.touches.length !== 2) return; event.preventDefault(); const nextDistance = Math.hypot(event.touches[0].clientX - event.touches[1].clientX, event.touches[0].clientY - event.touches[1].clientY); const previousDistance = pinchDistance.current; if (previousDistance && Math.abs(nextDistance / previousDistance - 1) > 0.01) changeZoom(nextDistance / previousDistance); pinchDistance.current = nextDistance }} onTouchEnd={() => { pinchDistance.current = null }} onPointerMove={(event) => { const rect = event.currentTarget.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width * 740; setSelectedIndex(Math.max(0, Math.min(chartCandles.length - 1, Math.floor((x - 20) / step)))) }} onPointerLeave={() => setSelectedIndex(null)} onKeyDown={(event) => { if (event.key === 'ArrowRight') setSelectedIndex((index) => Math.min(chartCandles.length - 1, (index ?? chartCandles.length - 1) + 1)); if (event.key === 'ArrowLeft') setSelectedIndex((index) => Math.max(0, (index ?? chartCandles.length) - 1)) }}>
      {[0, 1, 2, 3].map((index) => { const value = high - (high - low) * index / 3; return <g key={index}><line x1="22" x2="724" y1={y(value)} y2={y(value)} stroke="#e2e8f0" strokeDasharray="3 4"/><text x="24" y={y(value) - 3} fontSize="10" fill="#64748b">{priceText(value)}</text></g>})}
      {style === 'area' && <polygon points={`20,${top + priceHeight} ${closePoints} 720,${top + priceHeight}`} fill="#93c5fd" opacity=".35"/>}
      {style === 'line' || style === 'area' ? <polyline points={closePoints} fill="none" stroke="#2563eb" strokeWidth="2"/> : chartCandles.map((candle, index) => { const x = 20 + step * index + step / 2, rising = candle.close >= candle.open, candleTop = y(Math.max(candle.open, candle.close)), height = Math.max(2, Math.abs(y(candle.open) - y(candle.close))); return <g key={candle.openedAt} aria-hidden="true"><line x1={x} x2={x} y1={y(candle.high)} y2={y(candle.low)} stroke={rising ? '#e5484d' : '#2563eb'} strokeWidth="1.4"/><rect x={x - bodyWidth / 2} y={candleTop} width={bodyWidth} height={height} fill={rising ? '#e5484d' : '#2563eb'}/></g>})}
      {showSma7 && candles.length >= 7 && <polyline points={maPoints(7)} fill="none" stroke="#d97706" strokeWidth="1.8"/>}{showSma30 && candles.length >= 30 && <polyline points={maPoints(30)} fill="none" stroke="#7c3aed" strokeWidth="1.8"/>}
      {chartCandles.map((candle, index) => { const x = 20 + step * index + step / 2, rising = candle.close >= candle.open; return <rect key={`vol-${candle.openedAt}`} x={x - bodyWidth / 2} y={volumeTop + volumeHeight * (1 - candle.volume / maxVolume)} width={bodyWidth} height={volumeHeight * candle.volume / maxVolume} fill={rising ? '#fca5a5' : '#93c5fd'} aria-hidden="true"/>})}
      {ticker && <line x1="20" x2="722" y1={y(ticker.price)} y2={y(ticker.price)} stroke="#0f766e" strokeDasharray="5 4"/>}{selected && <line x1={20 + step * selectedIndex! + step / 2} x2={20 + step * selectedIndex! + step / 2} y1={top} y2={volumeTop + volumeHeight} stroke="#475569" strokeDasharray="3 3"/>}
    </svg><div className="grid gap-1 rounded-lg bg-slate-50 p-3 text-xs sm:grid-cols-3" aria-live="polite">{selected ? <><span>{timeText(selected.openedAt)}</span><span>시가 {priceText(selected.open)}</span><span>고가 {priceText(selected.high)}</span><span>저가 {priceText(selected.low)}</span><span>종가 {priceText(selected.close)}</span><span>거래량 {quantityText(selected.volume)} {symbol}</span></> : <span className="col-span-full">포인터나 방향키로 캔들을 선택하면 시가·고가·저가·종가·거래량을 확인할 수 있습니다.</span>}</div>
      <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-600"><span>상승</span><span>하락</span>{showSma7 && <span>SMA 7</span>}{showSma30 && <span>SMA 30</span>}<span>거래량</span><span>실시간 체결가</span></div></div> : <p className="mt-4 rounded-lg bg-slate-50 p-4 text-sm text-slate-600" role="status">{candleQuery.isPending ? '캔들 데이터를 불러오는 중입니다.' : '표시할 캔들 데이터가 없습니다.'}</p>}
    <div className="mt-4 grid gap-2 sm:grid-cols-4" aria-label="기술 지표"><Metric label="SMA(7)" value={sma7 ? priceText(sma7) : '데이터 부족'} /><Metric label="SMA(30)" value={sma30 ? priceText(sma30) : '데이터 부족'} /><Metric label="RSI(14)" value={rsi === null ? '데이터 부족' : rsi.toFixed(1)} /><Metric label="기간 변화" value={periodChange === null ? '데이터 부족' : `${periodChange >= 0 ? '+' : ''}${periodChange.toFixed(2)}%`} /></div>
    </section>
    <section className="grid items-start gap-3 lg:grid-cols-[minmax(0,1fr)_minmax(320px,.9fr)]" aria-label="호가와 주문">
    <section className="flex h-[800px] min-h-0 flex-col rounded-lg border border-slate-200 p-3" aria-labelledby="orderbook-heading"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold text-slate-900" id="orderbook-heading">호가</h3><div className="inline-flex rounded-lg bg-slate-100 p-1" role="group" aria-label="호가 표시 방식">{(['normal', 'cumulative'] as const).map((mode) => <button key={mode} type="button" aria-pressed={depth === mode} className={`rounded-md px-2 py-1.5 text-xs font-semibold transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-blue-700 sm:px-3 sm:text-sm ${depth === mode ? 'bg-slate-900 text-white shadow-sm' : 'text-slate-600 hover:bg-white'}`} onClick={() => setDepth(mode)}>{depth === mode && <span aria-hidden="true">✓ </span>}{mode === 'normal' ? '일반호가' : '누적호가'}</button>)}</div></div>
      {asks.length || bids.length ? <div className="mt-2"><div className="grid grid-cols-[minmax(0,1fr)_minmax(5rem,.8fr)_minmax(0,1fr)] gap-x-2 text-xs"><span className="pb-1 font-semibold text-slate-500">매도 잔량</span><span className="pb-1 text-center font-semibold text-slate-500">가격</span><span className="pb-1 text-right font-semibold text-slate-500">매수 잔량</span></div><div ref={orderbookViewport} aria-label="Price levels" className={`orderbook-scroll h-[680px] overflow-y-auto overscroll-contain ${scrollingOrderbook ? 'is-scrolling' : ''}`} onScroll={revealOrderbookScrollbar} style={{ overflowAnchor: 'none' }}><div className="grid grid-cols-[minmax(0,1fr)_minmax(5rem,.8fr)_minmax(0,1fr)] gap-x-2 text-xs">{asks.map((level, index) => { const levelIndex = asks.length - 1 - index; return <DepthRow key={level.askPrice} side="ASK" price={level.askPrice} quantity={depth === 'cumulative' ? askDepth[levelIndex] : level.askSize} maxSize={maxDepth} openPrice={ticker?.open ?? null} onPriceSelect={onPriceSelect} /> })}<div className="col-span-3 grid grid-cols-3 h-10 items-center border-y border-slate-200 bg-slate-50 px-2 py-0 text-center"><span className="text-slate-500">현재가</span><strong className="text-slate-950">{ticker ? priceText(ticker.price) : '수신 대기'}</strong><span className={ticker?.open && ticker.price >= ticker.open ? 'font-semibold text-rose-700' : 'font-semibold text-blue-700'}>{ticker?.open ? relativeText(relativeToOpen(ticker.price, ticker.open)) : '시가 대기'}</span></div>{bids.map((level, index) => <DepthRow key={level.bidPrice} side="BID" price={level.bidPrice} quantity={depth === 'cumulative' ? bidDepth[index] : level.bidSize} maxSize={maxDepth} openPrice={ticker?.open ?? null} onPriceSelect={onPriceSelect} />)}</div></div></div> : <p className="mt-2 rounded-lg bg-slate-50 p-3 text-sm text-slate-600" role="status">공개 호가 수신 대기 중입니다.</p>}
      <p className="mt-2 text-xs text-slate-500">{venues[exchange]} 공개 호가 스트림 · 개인 계정 주문과 무관</p></section>{orderPanel && <aside className="flex min-w-0 flex-col lg:h-[800px] lg:min-h-0" aria-label="Orders and public trades"><div className="min-h-0 lg:flex-1 lg:overflow-y-auto" aria-label="주문 메뉴">{orderPanel}</div><section className="min-h-0 rounded-lg border border-slate-200 p-3 lg:flex lg:flex-1 lg:flex-col"><div className="flex items-baseline justify-between gap-2"><h3 className="font-bold text-slate-900">실시간 시장 체결</h3><span className="text-xs text-slate-500">공개 시장 전체 · 내 주문 내역 아님</span></div><div className="mt-2 min-h-0 overflow-y-auto lg:flex-1">{trades.length ? <ol className="mt-2 divide-y divide-slate-100" aria-label="실시간 시장 체결 내역">{trades.slice(0, 8).map((trade) => <li key={`${exchange}-${trade.id}`} className="grid grid-cols-[minmax(0,1fr)_5.5rem_6.5rem] items-center gap-2 py-1.5 text-xs sm:text-sm"><time className="min-w-0 truncate text-slate-500 tabular-nums">{timeText(trade.timestamp)}</time><strong className="w-[5.5rem] whitespace-nowrap text-right tabular-nums">{priceText(trade.price)}</strong><span className={`w-[6.5rem] shrink-0 rounded px-1 py-1 text-center font-semibold tabular-nums whitespace-nowrap ${trade.side === 'BID' ? 'bg-rose-100 text-rose-800' : 'bg-blue-100 text-blue-800'}`} aria-label={`${trade.side === 'BID' ? '매수' : '매도'} 체결량`}>{trade.quantity.toLocaleString('ko-KR', { maximumFractionDigits: 4 })} {symbol}</span></li>)}</ol> : <p className="mt-2 rounded-lg bg-slate-50 p-3 text-sm text-slate-600" role="status">{stream.connected[exchange] ? '첫 공개 체결을 기다리는 중입니다.' : '실시간 체결 연결을 기다리는 중입니다.'}</p>}</div></section></aside>}</section></div>
    <section className="mt-8 rounded-xl border border-slate-200 bg-white p-4 shadow-sm" aria-labelledby="daily-market-heading"><div className="flex flex-wrap items-baseline justify-between gap-2"><h3 className="font-bold text-slate-900" id="daily-market-heading">{symbol} 일별 거래 통계</h3><span className="text-xs text-slate-500">거래소 공개 일봉 · 최근 7일</span></div>{dailyQuery.isPending ? <p className="mt-3 text-sm text-slate-500" role="status">일별 통계를 불러오는 중입니다.</p> : dailyQuery.isError ? <p className="mt-3 text-sm text-amber-800" role="status">일별 통계를 불러오지 못했습니다.</p> : <div className="mt-3 grid gap-4 xl:grid-cols-2">{dailyQuery.data?.map(([venue, rows]) => <div key={venue} className="min-w-0"><h4 className="mb-2 text-sm font-semibold">{venues[venue]}</h4><div className="overflow-x-auto"><table className="w-full min-w-[34rem] text-right text-xs sm:text-sm"><thead className="border-b border-slate-200 text-slate-500"><tr><th className="py-2 text-left font-medium">일자</th><th className="py-2 font-medium">종가</th><th className="py-2 font-medium">전일대비</th><th className="py-2 font-medium">거래량</th></tr></thead><tbody>{rows.slice(0, 7).map((row, index) => { const previous = rows[index + 1]; const change = previous?.close ? (row.close / previous.close - 1) * 100 : null; return <tr key={row.openedAt} className="border-b border-slate-100"><td className="py-2 text-left tabular-nums">{new Date(row.openedAt).toLocaleDateString('ko-KR')}</td><td className="py-2 tabular-nums">{priceText(row.close)}</td><td className={'py-2 tabular-nums ' + (change === null ? 'text-slate-500' : change >= 0 ? 'text-rose-700' : 'text-blue-700')}>{change === null ? '—' : (change > 0 ? '+' : '') + change.toFixed(2) + '%'}</td><td className="py-2 tabular-nums">{quantityText(row.volume)} {symbol}</td></tr>})}</tbody></table></div></div>)}</div>}</section>
    <div className="mt-5"><MarketDiscussionBoard symbol={symbol} token={token} /></div><p className="mt-3 text-xs leading-5 text-slate-500">출처: {venues[exchange]} 공개 WebSocket(시세·체결·호가), 공개 캔들 API. 지표는 단순 이동평균과 14기간 RSI의 참고 값이며 매매 추천이나 주문 신호가 아닙니다.</p>
  </section>
}

function DepthRow({ side, price, quantity, maxSize, openPrice, onPriceSelect }: { side: 'ASK' | 'BID'; price: number; quantity: number; maxSize: number; openPrice: number | null; onPriceSelect?: (price: number, side: 'BUY' | 'SELL') => void }) {
  const ask = side === 'ASK'
  const amount = <span className={ask ? 'relative flex h-10 items-center overflow-hidden rounded px-2 text-right text-rose-800' : 'relative flex h-10 items-center overflow-hidden rounded px-2 text-left text-blue-800'}><i aria-hidden="true" className={ask ? 'absolute inset-y-0 right-0 bg-rose-200/60' : 'absolute inset-y-0 left-0 bg-blue-200/60'} style={{ width: (Math.min(100, quantity / maxSize * 100)) + '%' }}/><b className="relative" data-testid={ask ? 'ask-quantity' : 'bid-quantity'}>{quantityText(quantity)}</b></span>
  const priceCell = <span className={ask ? 'flex h-10 items-center justify-center text-center font-semibold text-rose-800' : 'flex h-10 items-center justify-center text-center font-semibold text-blue-800'}>{onPriceSelect ? <button type="button" className="block w-full hover:underline" aria-label={(ask ? '매도' : '매수') + ' 호가 ' + priceText(price) + ' 선택'} onClick={() => onPriceSelect(price, ask ? 'BUY' : 'SELL')}><QuotePrice price={price} openPrice={openPrice} /></button> : <QuotePrice price={price} openPrice={openPrice} />}</span>
  return <div className="col-span-3 grid h-10 grid-cols-[minmax(0,1fr)_minmax(5rem,.8fr)_minmax(0,1fr)] items-center border-b border-slate-200/80">{ask ? amount : <span aria-hidden="true"/>}{priceCell}{ask ? <span aria-hidden="true"/> : amount}</div>
}
function QuotePrice({ price, openPrice }: { price: number; openPrice: number | null }) { const change = relativeToOpen(price, openPrice); return <span className="block"><span>{priceText(price)}</span><small className={`block text-[10px] leading-4 ${change === null ? 'text-slate-500' : change >= 0 ? 'text-rose-700' : 'text-blue-700'}`}>{relativeText(change)}</small></span> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><strong className="mt-1 block break-words text-sm text-slate-900">{value}</strong></div> }
